INSERT INTO USUARIO (NAME ,EMAIL, PASSWORD ) VALUES ('GASPAR', 'GASPAR@GMAIL.COM', '1234')
INSERT INTO USUARIO (NAME ,EMAIL, PASSWORD ) VALUES ('AGUSTIN', 'AGUSTIN@GMAIL.COM', 'AGUSTIN')
INSERT INTO USUARIO (NAME ,EMAIL, PASSWORD ) VALUES ('MARIA', 'MARIA@GMAIL.COM', 'MARIA')
INSERT INTO USUARIO (NAME ,EMAIL, PASSWORD ) VALUES ('ANGELICA', 'ANGELICA@GMAIL.COM', 'ANGELICA')
INSERT INTO USUARIO (NAME ,EMAIL, PASSWORD ) VALUES ('VICENTE', 'VICENTE@GMAIL.COM', 'VICENTE')

INSERT INTO PHONE (NUMBER ,CITYCODE, CONTRYCODE, ID_USUARIO) VALUES (2,3,4, 1)
INSERT INTO PHONE (NUMBER ,CITYCODE, CONTRYCODE, ID_USUARIO) VALUES (2,3,4,2)