DROP TABLE IF EXISTS PHONE;
DROP TABLE IF EXISTS USUARIO;



CREATE TABLE USUARIO(
	ID_USUARIO VARCHAR PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(40) NOT NULL,
	FECHA_CREACION DATE,
	FECHA_MODIFICACION DATE,
	FECHA_INGRESO DATE,
	ACTIVO BOOLEAN,
	TOKEN VARCHAR 
);

CREATE TABLE PHONE(
	ID_PHONE INT AUTO_INCREMENT PRIMARY KEY,
	NUMBER INT ,
	CITYCODE INT ,
	CONTRYCODE INT ,
	ID_USUARIO VARCHAR,
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
)